
Category.destroy_all()
Item.destroy_all()

Category.create(name: "Italian Specialties")
Category.create(name: "Deli Sandwhiches & Subs")
Category.create(name: "Hot Subs/Sandwhiches")
Category.create(name: "Entrees")
Category.create(name: "Salads")
Category.create(name: "Kids Meal")
Category.create(name: "Chips & Sides")
Category.create(name: "Specialty Drinks")
Category.create(name: "Desserts")
Category.create(name: "Groceries")

#ITALIAN SPECIALTIES
Item.create(name: "Classic Italian", regular: 8.99, large: 12.99, ingredients: "Mortadella, Imported Ham, Capocollo, Salami, Pepperoni & Provolone", category_id: 1)
Item.create(name: "Spicy Italian", regular: 8.99, large: 12.99, ingredients: "Spicy Capocollo, Genoa Salami & Provolone", category_id: 1)
Item.create(name: "Italian Stallion", regular: 8.99, large: 12.99, ingredients: "Prosciuttini Ham, Genoa Salami and Provolone", category_id: 1)
Item.create(name: "Il Miastro", regular: 8.99, large: 12.99, ingredients: "Prosciutto, Fresh Mozzarella, Tomato, Oil & Vinegar, Salt & Pepper and Oregano", category_id: 1)
Item.create(name: "Super King", regular: 8.99, large: 12.99, ingredients: "Mortadella, Imported Ham, Genoa Salami & Provolone", category_id: 1)
Item.create(name: "Crazy Italian", regular: 8.99, large: 12.99, ingredients: "Mortadella, Genoa Salami, Capocollo, and Provolone", category_id: 1)
Item.create(name: "Milano", regular: 8.99, large: 12.99, ingredients: "Mortadella, Soppressata, Capocollo & Provolone", category_id: 1)
Item.create(name: "Fresh Mozzarella and Tomato", regular: 6.99, large: 10.99, ingredients: "Fresh Mozzarella, Sliced Tomato, Oil & Vinegar, Oregano, and Salt & Pepper", category_id: 1)
Item.create(name: "Zap", regular: 8.99, large: 12.99, ingredients: "Pepperoni, Genoa Salami, Imported Ham & Provolone", category_id: 1)
Item.create(name: "Super Zap", regular: 8.99, large: 12.99, ingredients: "Pepperoni, Genoa Salami, Imported Ham, Turkey & Provolone", category_id: 1)

#DELI SANDWICHES AND SUBS
Item.create(name: "The Big A", regular: 8.99, large: 12.99, ingredients: "Double meat: Roast Beef, Turkey & Provolone Cheese", category_id: 2)
Item.create(name: "12\" Super Big A", regular: null, large: 12.99, ingredients: "One of our BIGGEST. Roast Beef, Turkey, Imported Ham, & Provolone Cheese", category_id: 2)
Item.create(name: "Smokey", regular: 8.99, large: 12.99, ingredients: "Double meat. Virginia Smoked Ham, Smoked Turkey & Provolone Cheese", category_id: 2)
Item.create(name: "Salami, Tuna and Cheese", regular: 8.99, large: 12.99, ingredients: "Thinly sliced Genoa Salami & Provolone Cheese, topped with our homemade Tuna Salad", category_id: 2)
Item.create(name: "Turkey", regular: 6.99, large: 10.99, ingredients: "", category_id: 2)
Item.create(name: "Imported Ham", regular: 6.99, large: 10.99, ingredients: "", category_id: 2)
Item.create(name: "Turkey & Ham", regular: 8.99, large: 12.99, ingredients: "Double Meat", category_id: 2)
Item.create(name: "Roast Beef", regular: 8.49, large: 12.49, ingredients: "Mortadella, Salami and Provolone", category_id: 2)
Item.create(name: "Italian Hoagie", regular: 6.99, large: 10.99, ingredients: "Pepperoni, Genoa Salami, Imported Ham & Provolone", category_id: 2)
Item.create(name: "Chicken Salad", regular: 6.99, large: 10.99, ingredients: "Fresh, homemade classic Chicken Salad", category_id: 2)
Item.create(name: "Tuna Salad", regular: 6.99, large: 10.99, ingredients: "Homemade Tuna Salad with celery & spices", category_id: 2)
Item.create(name: "Egg Salad", regular: 6.49, large: 10.99, ingredients: "Made to order Egg Salad.. simply done with Mayo, salt & pepper", category_id: 2)
Item.create(name: "Corned Beef", regular: 8.49, large: 12.49, ingredients: "", category_id: 2)
Item.create(name: "Virginia Smoked Ham", regular: 6.99, large: 10.99, ingredients: "", category_id: 2)
Item.create(name: "Smoked Turkey", regular: 6.99, large: 10.99, ingredients: "", category_id: 2)
Item.create(name: "Bologna", regular: 6.99, large: 10.99, ingredients: "100% Beef", category_id: 2)
Item.create(name: "Veggie", regular: 6.49, large: 10.99, ingredients: "Provolone, American, Lettuce, Tomato, Onion, Banana Peppers, Sweet Peppers, Mushrooms, Mayo, Oil & Vinegar, Oregano and Salt & Pepper - Adjust as needed", category_id: 2)
Item.create(name: "Proscuitto", regular: 8.49, large: 12.49, ingredients: "Thinly sliced", category_id: 2)
Item.create(name: "Capocollo", regular: 6.99, large: 10.99, ingredients: "Sweet & Smokey", category_id: 2)
Item.create(name: "Mortadella", regular: 6.99, large: 10.99, ingredients: "", category_id: 2)
Item.create(name: "Pepperoni", regular: 6.99, large: 10.99, ingredients: "", category_id: 2)
Item.create(name: "Genoa Salami", regular: 6.99, large: 10.99, ingredients: "", category_id: 2)
Item.create(name: "Soppressata", regular: 8.49, large: 12.49, ingredients: "Spicy wine & garlic seasoned Salami", category_id: 2)
Item.create(name: "Spicy Capocollo", regular: 8.49, large: 12.49, ingredients: "Soft, smokey & spicy capocollo", category_id: 2)
Item.create(name: "Pastrami", regular: 8.49, large: 12.49, ingredients: "Hot or cold - Great with Swiss cheese", category_id: 2)
Item.create(name: "Turkey Pastrami", regular: 8.49, large: 12.49, ingredients: "Tastes great, hot or cold", category_id: 2)
Item.create(name: "Cheese Sub", regular: 6.99, large: 10.99, ingredients: "Mortadella, Soppressata, Capocollo & Provolone", category_id: 2)

#HOT SUBS/SANDWICHES
Item.create(name: "Steak and Cheese Sub", regular: 7.49, large: 11.99, ingredients: "Rib-eye Steak topped with cheese of your choice", category_id: 3)
Item.create(name: "Steak, Ham and Cheese Sub", regular: 8.99, large: 12.99, ingredients: "Rib-Eye Steak, Imported Ham & Provolone Cheese", category_id: 3)
Item.create(name: "Steak, Pepperoni and Cheese Sub", regular: 8.99, large: 12.99, ingredients: "Thinly-sliced Pepperoni, topped with Rib-eye Steak all covered with Melted Provolone Cheese", category_id: 3)
Item.create(name: "Chicken Cheesesteak Sub", regular: 6.99, large: 10.99, ingredients: "Grilled Chicken Breast, topped with Provolone Cheese & toasted to perfection", category_id: 3)
Item.create(name: "Chicken, Bacon, Cheddar & Ranch Sub", regular: 8.99, large: 12.99, ingredients: "Grilled Chicken, Crispy Bacon, Melted Cheddar, all topped with Ranch Dressing", category_id: 3)
Item.create(name: "Grilled Chicken Sub", regular: 6.99, large: 10.99, ingredients: "Grilled Chicken Breast on Toasted Bread, with Cheese & Toppings of your choice", category_id: 3)
Item.create(name: "Chicken Parmesan Sub", regular: 6.99, large: 10.99, ingredients: "Grilled Chicken Breast covered in Marinara Sauce w/ Melted Provolone & Parmesan Cheese", category_id: 3)
Item.create(name: "Eggplant Parmesan Sub", regular: 6.99, large: 10.99, ingredients: "Breaded Eggplant & Marinara topped with Melted Provolone & Parmesan Cheese", category_id: 3)
Item.create(name: "BLT", regular: 6.99, large: 10.99, ingredients: "Crispy Bacon, Lettuce & Tomato on Toasted Bread", category_id: 3)
#Check Reuben listing for caveats in pricing
Item.create(name: "Reuben", regular: 7.99, large: 11.99, ingredients: "Corned Beef, Sauerkraut, Swiss Cheese & Thousand Island, all on toasty Rye Bread - Classic. (Rye only available as a small size)", category_id: 3)
Item.create(name: "New Yorker", regular: 8.49, large: 12.49, ingredients: "Pastrami, Corned Beef, Swiss Cheese & Coleslaw", category_id: 3)
Item.create(name: "Meatball and Cheese Sub", regular: 6.99, large: 10.99, ingredients: "Italian Meatballs w/ Marinara Sauce & Provolone Cheese (Beef & Pork)", category_id: 3)
Item.create(name: "Meatball, Pepperoni & Cheese Sub", regular: 8.99, large: 12.99, ingredients: "Toasty bread, thinly sliced Pepperoni, Italian Meatballs, topped with Marinara Sauce, all covered with melted Provolone Cheese", category_id: 3)
Item.create(name: "Sausage and Cheese Sub", regular: 6.99, large: 10.99, ingredients: "All Pork Italian Sausage, topped with Marinara & Provolone Cheese", category_id: 3)
Item.create(name: "Sausage, Meatball and Cheese Sub", regular: 6.99, large: 10.99, ingredients: "Pork Sausage, Italian Meatballs, Marinara & Provolone Cheese", category_id: 3)
Item.create(name: "Spicy Capocollo", regular: 8.49, large: 12.49, ingredients: "Soft, smokey & spicy capocollo", category_id: 3)
Item.create(name: "Gyro", regular: 6.99, large: null, ingredients: "Greek Classic on Pita Bread - Available in Lamb or Chicken", category_id: 3)
Item.create(name: "BBQ Sub", regular: 6.99, large: 10.99, ingredients: "Texas-Style \"Cowboy's\" Beef BBQ, Available w/ Cheese & Coleslaw", category_id: 3)
Item.create(name: "Pizza Steak Sub", regular: 7.49, large: 11.99, ingredients: "Rib-Eye Steak topped with Marinara Sauce & Provolone Cheese", category_id: 3)

#ENTREES
Item.create(name: "Chicken Parmesan Entree", regular: 11.99, large: null, ingredients: "Served w/ Pasta, House Salad & Garlic Bread", category_id: 4)
Item.create(name: "Beef Lasahna", regular: 11.99, large: null, ingredients: "Served w/ House Salad & Garlic Bread", category_id: 4)
Item.create(name: "Manicotti", regular: 11.99, large: , ingredients: "Served w/ House Salad & Garlic Bread", category_id: 4)
Item.create(name: "Ravioli", regular: 11.99, large: null, ingredients: "Served w/ House Salad & Garlic Bread", category_id: 4)
Item.create(name: "Spaghetti and Meatballs", regular: 11.99, large: null, ingredients: "Served w/ House Salad & Garlic Bread", category_id: 4)
Item.create(name: "Tortellini", regular: 11.99, large: null, ingredients: "Served w/ House Salad & Garlic Bread", category_id: 4)

#SALADS
Item.create(name: "Antipasto Salad", regular: 10.49, large: null, ingredients: "Mortadella, Capocollo, Imported Ham, Pepperoni, Genoa Salami, & Provolone Cheese. Lettuce, Tomato, Onion, & Peppers. Housemade Vinaigrette", category_id: 5)
Item.create(name: "Chef Salad", regular: 8.99, large: null, ingredients: "Turkey, Ham, Provolone Cheese, Hard-Boiled Egg, Lettuce, Tomato, Onion, Peppers & Dressing of your Choice", category_id: 5)
Item.create(name: "Grilled Chicken Salad", regular: 8.49, large: null, ingredients: "Grilled Chicken Breast, Hard Boiled Egg, Lettuce, Tomato, Onion, Peppers - Choice of Dressing", category_id: 5)
Item.create(name: "Greek Salad", regular: 8.49, large: null, ingredients: "Greek Marinated Black Olives, Feta Cheese, Peppers, Onion, Tomato, Oregano, Salt & Pepper on a Bed of Lettuce. - Homemade Vinaigrette", category_id: 5)
Item.create(name: "Greek Salad with Grilled Chicken", regular: 10.49, large: null, ingredients: "Grilled Chicken Breast, Greek Marinated Black Olives, Feta Cheese, Peppers, Onion, Tomato, Oregano, Salt & Pepper on a Bed of Lettuce. - Homemade Vinaigrette", category_id: 5)
Item.create(name: "Greek Salad with Gyro Meat", regular: 10.49, large: null, ingredients: "Lamb Gyro Meat, Greek Marinated Black Olives, Feta Cheese, Peppers, Onion, Tomato, Oregano, Salt & Pepper on a Bed of Lettuce. - Homemade Vinaigrette", category_id: 5)
Item.create(name: "Fresh Mozzarella & Tomato Salad", regular: 8.49, large: null, ingredients: "Sliced Fresh Mozzarella, Sliced Tomato, Oregano, Salt & Pepper, on a bed of Lettuce - Homemade Vinaigrette", category_id: 5)
Item.create(name: "Chicken Salad", regular: 8.49, large: null, ingredients: "Housemade Chicken Salad on Top of a bed of Lettuce, Tomato, Onion, Peppers. Dressing on the side", category_id: 5)
Item.create(name: "Tuna Salad", regular: 8.49, large: null, ingredients: "Housemade Tuna Salad on Top of a bed of Lettuce, Tomato, Onion, Peppers. Dressing on the side", category_id: 5)
Item.create(name: "Veggie Salad", regular: 8.49, large: null, ingredients: "American & Provolone Cheeses, Lettuce, Tomato, Onion, Peppers, Sweet Peppers, Mushrooms - Dressing of your choice", category_id: 5)

#Kids Meal
Item.create(name: "Kids Meal", regular: 6.99, large: null, ingredients: "Kids Sized Sandwich, Small Bag of Chips & a Canned Drink", category_id: 5)

